version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NEO4J_URI=neo4j://db:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=superlongsecret
      - |
        API_DOCUMENTATION=API documentation
        This API is useful for answering questions about Python coding.
    depends_on:
      - db
  db:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/superlongsecret
    ports:
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
